### ISSUE TITLE
Camera Image not auto-generated

### ISSUE THREAD

**Issue by jabb1123** [santosfamilyfoundation/SantosGUI#33]
I noticed that when we create a new project, the camera image is not created properly. @runnersaw  can confirm this issue? We need to look into how `cv2` pulls the image and see what is causing the bug. Current work around is to manually add the camera image to the homography folder after creating the project, then using the open camera view button to link to that picture. 

Small side note about the open camera view button. It does not automatically move the picture into the homography folder. @dcelik informed me that this was a small part of a bigger issue, so it is not the focus of this issue.

![screen shot 2017-02-08 at 9 44 53 pm](https://cloud.githubusercontent.com/assets/6538204/22767207/e1e306d4-ee47-11e6-92a6-bd8cee192a72.png)

This code is found in `pm.py` on in this repository. This is the suspect block because the else trips and the error message clipped is printed. @runnersaw can confirm they see this error too?

**Comment by runnersaw** [comment]
I saw this same error. I fixed this by:

1. Uninstalling opencv from `conda uninstall opencv`.
2. Installing opencv by downloading the package online and extracting to `C:\`.
3. Copying `cv2.pyd` from `C:\opencv\build\python\2.7\x64` to my `site-packages` folder (which is `C:\Anaconda2\Lib\site-packages` for me).

**Comment by runnersaw** [comment]
I believe this was resolved by the move from `cv2` to `ffmpeg` in #93.
