### ISSUE TITLE
Results does not open expected window on download

### ISSUE THREAD

**Issue by segerphilip** [santosfamilyfoundation/SantosGUI#66]
<img width="693" alt="screen shot 2017-02-15 at 2 46 44 pm" src="https://cloud.githubusercontent.com/assets/5553994/22992423/ae1457e0-f38d-11e6-90d6-91f79095f22f.png">

**Comment by jabb1123** [comment]
More information required. Please provide OS, package versions, etc.

**Comment by segerphilip** [comment]
OS: Ubuntu 14.04
xdg-open does not take -- as extra args. Should just be `xdg-open project_dir`.
